Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.define "webserver" do |h|
    h.vm.network "private_network", ip: "192.168.50.4"
    h.vm.hostname = "webserver"
  end
end
